Fix #137 missing layout paragraphs settings.
localgovdrupal/localgov_paragraphs pull request #138
Opened 2023-04-25 09:49 UTC by ekes

Guess the thing to test is:-

If you happen to have a db for a site with the broken modal run the update on it.
Otherwise maybe break it by deleting the config/sync/layout_paragraphs.modal_settings.php and drush cim to remove it, then running updates.
Also run updates on a good site, with different setting maybe, to check it doesn't change anything.

In all cases modal should have correct settings and work after the updat.

2023-04-26 12:11 UTC, stephen-cox requested changes
I've been able to replicate the issue by exporting the config from my local site, deleting the `config/sync/layout_paragraphs.modal_settings.yml` file and then re-importing the site config.

This code did reinstate the missing config, but there were a couple of issues:

1. Drupal didn't find the post update hook so wasn't being run with database updates; I'm not sure why as it looks okay to me. To test it I ran the function with Drush using `drush ev "module_load_include('post_update.php', 'localgov_paragraphs_layout'); localgov_paragraphs_layout_post_update_fix_missing_layout_paragraphs_setting();"`
2. There's a minor change to the config needed.

2023-04-26 12:11 UTC, stephen-cox commented on modules/localgov_paragraphs_layout/localgov_paragraphs_layout.post_update.php
> +    $config->set('width', '90');
This should by 90%, otherwise it looks to default to 90 pixels.

2023-05-10 09:13 UTC, keelanfh commented
Didn't review this as we just changed the settings manually.

2023-05-15 13:46 UTC, stephen-cox commented on modules/localgov_paragraphs_layout/localgov_paragraphs_layout.post_update.php
> +    $config->set('width', '90');
Fixed thanks

2023-05-15 13:49 UTC, stephen-cox reviewed
I've just tried this again and the post update hook to run.

@finnlewis or someone else able to check this?

2023-05-15 13:55 UTC, ekes commented
Steps to test.

- Have the standard checkout of localgov_paragraphs checked out; run a site install.
- Enable the localgov_paragraphs_layout module
- Then checkout this branch
- Then run updb

2023-05-22 13:25 UTC, finnlewis commented
I'll take a look at this soon

2023-06-12 09:18 UTC, ekes commented
:bellhop_bell:

2023-06-14 14:25 UTC, stephen-cox approved these changes
Must have messed the order of things - working fine

2023-06-19 13:50 UTC, merged